name: CI

on:
  push:
    branches: ["main", "restore-full"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Run tests
        run: pytest -q
